name: FastAPI CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 2. ¿Qué tareas va a realizar?
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el repositorio
      uses: actions/checkout@v4

    # Paso B: Instala Python
    - name: Configurar Python 3.14
      uses: actions/setup-python@v5
      with:
        python-version: "3.14" # Cambia esto si usas otra versión localmente

    # Paso C: FastAPI, Uvicorn, SQLAlchemy y tus herramientas de testing
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Aseguramos que pytest y httpx estén instalados para las pruebas
        pip install pytest httpx 

    # Paso D: Ejecuta el archivo test_main.py que creaste antes
    - name: Ejecutar pruebas con Pytest
      run: |
        pytest