name: FastAPI CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          # Definimos credenciales temporales para el servidor de GitHub
          POSTGRES_USER: user_test
          POSTGRES_PASSWORD: password_test
          POSTGRES_DB: db_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt
        pip install pytest httpx

    - name: Ejecutar pruebas
      env:
        # Construimos la URL que tu Python leerá con os.getenv
        DATABASE_URL: postgresql://user_test:password_test@localhost:5432/db_test
      run: |
        pytest